name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 9
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          cache: 'maven'
          java-version: 9
          architecture: x64

      - name: Setup TCC database latest
        shell: bash
        # Manipulate TCC, see https://github.com/actions/virtual-environments/issues/553#issuecomment-648109166
        # in order to allow AppleScript automation of Spotify.app
        if: matrix.os == 'macos-latest'
        run: |
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" .schema
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, auth_value, auth_reason, auth_version, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 2, 3, 1, 0, 'com.spotify.client')"

      - name: Setup TCC database macOS 10.15
        shell: bash
        if: matrix.os == 'macos-10.15'
        # Manipulate TCC, see https://github.com/actions/virtual-environments/issues/553#issuecomment-648109166
        # in order to allow AppleScript automation of Spotify.app
        run: |
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" .schema
          sqlite3 "/Users/runner/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '/bin/bash', 1, 1, 1, 0, 'com.spotify.client')"

      - name: Build/test code with Maven
        shell: bash
        # Manipulate TCC, see https://github.com/actions/virtual-environments/issues/553#issuecomment-648109166
        # in order to allow AppleScript automation of Spotify.app
        run: |
          mvn -B install --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
